"""Theme package: palette data, accessibility rules, and Qt styling.

Split out of a single 2 100-line module. The public names are unchanged, so
`from crapcleaner.gui.theme import apply_theme` keeps working; palettes now come
from data files (see :mod:`crapcleaner.gui.theme.palettes`).
"""

from crapcleaner.gui.theme.palettes import (
    _TEXT_BACKGROUNDS,
    _TEXT_ROLES,
    BUILTIN_THEME_IDS,
    CONTRAST_EXEMPTIONS,
    DARK,
    MIN_TEXT_CONTRAST,
    PALETTES,
    THEME_CATEGORIES,
    THEME_CATEGORY_MAP,
    THEME_DESCRIPTIONS,
    THEME_LABELS,
    THEME_PATHS,
    THEME_SOURCES,
    THEMES,
    USER_CATEGORY,
    accessible_palette,
    delete_user_theme,
    derive_ink,
    get_custom_theme_palette,
    get_theme_category,
    get_theme_category_label,
    get_theme_description,
    get_theme_swatches,
    invalidate_custom_theme_cache,
    is_dark_theme,
    is_user_theme,
    palette_for,
    reload_themes,
    save_user_theme,
    slugify,
    theme_generator,
    theme_label,
    user_theme_dir,
    user_theme_path,
    user_themes,
)
from crapcleaner.gui.theme.stylesheet import (
    _build_stylesheet,
    accent_color,
    apply_theme,
    color,
    fade_theme_change,
    make_window_icon,
)

__all__ = [
    "CONTRAST_EXEMPTIONS",
    "BUILTIN_THEME_IDS",
    "THEME_PATHS",
    "USER_CATEGORY",
    "delete_user_theme",
    "derive_ink",
    "is_user_theme",
    "save_user_theme",
    "slugify",
    "user_theme_path",
    "user_themes",
    "DARK",
    "MIN_TEXT_CONTRAST",
    "PALETTES",
    "THEMES",
    "THEME_CATEGORIES",
    "THEME_CATEGORY_MAP",
    "THEME_DESCRIPTIONS",
    "THEME_LABELS",
    "THEME_SOURCES",
    "_TEXT_BACKGROUNDS",
    "_TEXT_ROLES",
    "_build_stylesheet",
    "accent_color",
    "accessible_palette",
    "apply_theme",
    "color",
    "fade_theme_change",
    "get_custom_theme_palette",
    "get_theme_category",
    "get_theme_category_label",
    "get_theme_description",
    "get_theme_swatches",
    "invalidate_custom_theme_cache",
    "is_dark_theme",
    "make_window_icon",
    "palette_for",
    "reload_themes",
    "theme_generator",
    "theme_label",
    "user_theme_dir",
]
