"""GPU shader cache cleanup categories."""

import os

from crapcleaner.models.category import CacheTarget, CleanupCategory, SafetyLevel
from crapcleaner.utils.platform import (
    get_appdata,
    get_local_appdata,
    get_program_files_x86,
)

SHADER_WARNING = (
    "Shader caches are normally safe to rebuild, but games and applications may "
    "temporarily experience longer loading times or shader compilation after cleanup."
)


def _steam_libraries() -> list[str]:
    libraries = []
    base = os.path.join(get_program_files_x86(), "Steam", "steamapps")
    if os.path.isdir(base):
        libraries.append(base)
        vdf = os.path.join(base, "libraryfolders.vdf")
        if os.path.isfile(vdf):
            try:
                with open(vdf, encoding="utf-8", errors="replace") as fh:
                    for line in fh:
                        line = line.strip()
                        if '"path"' in line:
                            import re

                            match = re.search(r'"path"\s+"(.*)"', line)
                            if match:
                                p = os.path.join(match.group(1), "steamapps")
                                if os.path.isdir(p) and p not in libraries:
                                    libraries.append(p)
            except OSError:
                pass
    return libraries


def get_categories() -> list[CleanupCategory]:
    local = get_local_appdata()
    appdata = get_appdata()

    categories = []

    nvidia_targets = []
    for sub in ("DXCache", "GLCache", "NV_Cache", "ComputeCache"):
        p = os.path.join(local, "NVIDIA", sub)
        if os.path.isdir(p):
            nvidia_targets.append(CacheTarget(path=p))
    if nvidia_targets:
        categories.append(
            CleanupCategory(
                id="nvidia_shader_cache",
                name="NVIDIA shader cache",
                group="GPU",
                description="NVIDIA shader and driver caches (DXCache, GLCache). " + SHADER_WARNING,
                safety_level=SafetyLevel.LOW_RISK,
                targets=nvidia_targets,
            )
        )

    amd_targets = []
    for sub in ("DxCache", "GLCache"):
        p = os.path.join(local, "AMD", sub)
        if os.path.isdir(p):
            amd_targets.append(CacheTarget(path=p))
    if amd_targets:
        categories.append(
            CleanupCategory(
                id="amd_shader_cache",
                name="AMD shader caches",
                group="GPU",
                description="AMD shader caches. " + SHADER_WARNING,
                safety_level=SafetyLevel.LOW_RISK,
                targets=amd_targets,
            )
        )

    vulkan_targets = []
    vulkan_root = os.path.join(local, "Vulkan")
    if os.path.isdir(vulkan_root):
        vulkan_targets.append(CacheTarget(path=vulkan_root))
    gfx_cache = os.path.join(appdata, "Vulkan")
    if os.path.isdir(gfx_cache):
        vulkan_targets.append(CacheTarget(path=gfx_cache))
    if vulkan_targets:
        categories.append(
            CleanupCategory(
                id="vulkan_shader_cache",
                name="Vulkan shader caches",
                group="GPU",
                description="Vulkan pipeline caches. " + SHADER_WARNING,
                safety_level=SafetyLevel.LOW_RISK,
                targets=vulkan_targets,
            )
        )

    steam_shader_targets = []
    steam_appcache_targets = []
    for library in _steam_libraries():
        shadercache = os.path.join(library, "shadercache")
        if os.path.isdir(shadercache):
            steam_shader_targets.append(CacheTarget(path=shadercache))
        appcache = os.path.join(library, "appcache")
        if os.path.isdir(appcache):
            steam_appcache_targets.append(CacheTarget(path=appcache))

    if steam_shader_targets:
        categories.append(
            CleanupCategory(
                id="steam_shader_cache",
                name="Steam shader caches",
                group="GPU",
                description="Per-game shader caches managed by Steam. Recompiled on the next game launch. "
                + SHADER_WARNING,
                safety_level=SafetyLevel.LOW_RISK,
                targets=steam_shader_targets,
            )
        )

    if steam_appcache_targets:
        categories.append(
            CleanupCategory(
                id="steam_appcache",
                name="Steam app cache",
                group="GPU",
                description="Steam client cache data. Regenerated by Steam automatically.",
                safety_level=SafetyLevel.LOW_RISK,
                targets=steam_appcache_targets,
            )
        )

    return categories
