"""GPU shader cache cleanup categories."""

import os

from crapcleaner.models.category import CacheTarget, CleanupCategory, SafetyLevel
from crapcleaner.utils.platform import (
    get_appdata,
    get_local_appdata,
    get_program_files_x86,
    get_user_profile,
    is_linux,
    is_windows,
)

SHADER_WARNING = (
    "Shader caches are normally safe to rebuild, but games and applications may "
    "temporarily experience longer loading times or shader compilation after cleanup."
)


def _steam_libraries() -> list[str]:
    libraries = []
    base = os.path.join(get_program_files_x86(), "Steam", "steamapps")
    if os.path.isdir(base):
        libraries.append(base)
        vdf = os.path.join(base, "libraryfolders.vdf")
        if os.path.isfile(vdf):
            try:
                with open(vdf, encoding="utf-8", errors="replace") as fh:
                    for line in fh:
                        line = line.strip()
                        if '"path"' in line:
                            import re

                            match = re.search(r'"path"\s+"(.*)"', line)
                            if match:
                                p = os.path.join(match.group(1), "steamapps")
                                if os.path.isdir(p) and p not in libraries:
                                    libraries.append(p)
            except OSError:
                pass
    return libraries


def _linux_shader_categories() -> list[CleanupCategory]:
    """Shader caches as they exist on Linux.

    The Windows paths this module builds land under ~/.cache on Linux and match
    nothing, so the whole GPU group reported zero while the caches that actually
    grow - Mesa's on-disk shader cache above all - were never offered.
    """
    home = get_user_profile()
    cache = get_local_appdata()  # ~/.cache, or $XDG_CACHE_HOME

    mesa_targets = [
        CacheTarget(path=os.path.join(cache, name))
        for name in ("mesa_shader_cache", "mesa_shader_cache_db", "radv_builtin_shaders")
    ]
    nvidia_targets = [
        CacheTarget(path=os.path.join(home, ".nv", "GLCache")),
        CacheTarget(path=os.path.join(home, ".nv", "ComputeCache")),
        CacheTarget(path=os.path.join(cache, "nvidia", "GLCache")),
    ]
    steam_shader_targets = [
        CacheTarget(path=os.path.join(root, "steamapps", "shadercache"))
        for root in (
            os.path.join(home, ".local", "share", "Steam"),
            os.path.join(home, ".steam", "steam"),
            os.path.join(
                home, ".var", "app", "com.valvesoftware.Steam", ".local", "share", "Steam"
            ),
        )
    ]

    categories: list[CleanupCategory] = []
    if any(t.exists for t in mesa_targets):
        categories.append(
            CleanupCategory(
                id="mesa_shader_cache",
                name="Mesa shader cache",
                group="GPU",
                description="Compiled shader cache for Intel, AMD, and other Mesa drivers.",
                safety_level=SafetyLevel.LOW_RISK,
                what_it_contains="Shaders Mesa compiled for games and applications you have run.",
                why_it_grows="Every new game, driver update, or shader variant adds entries.",
                why_safe_to_delete="Purely derived data; the driver recompiles what it needs.",
                regeneration_behavior="Recompiled on demand - expect brief stutter the first time a game runs.",
                reversible=True,
                targets=mesa_targets,
            )
        )
    if any(t.exists for t in nvidia_targets):
        categories.append(
            CleanupCategory(
                id="nvidia_glcache_linux",
                name="NVIDIA GL & compute cache",
                group="GPU",
                description="Compiled OpenGL and CUDA kernel caches for the NVIDIA driver.",
                safety_level=SafetyLevel.LOW_RISK,
                what_it_contains="Cached OpenGL shader and compute kernel binaries.",
                why_it_grows="Grows with each application and driver version.",
                why_safe_to_delete="Regenerated by the driver; nothing here is user data.",
                regeneration_behavior="Rebuilt on next run of each application.",
                reversible=True,
                targets=nvidia_targets,
            )
        )
    if any(t.exists for t in steam_shader_targets):
        categories.append(
            CleanupCategory(
                id="steam_shader_cache_linux",
                name="Steam & Proton shader cache",
                group="GPU",
                description="Pre-compiled shader caches Steam downloads and Proton generates.",
                safety_level=SafetyLevel.LOW_RISK,
                what_it_contains="Per-game shader caches, including Proton's DXVK and VKD3D output.",
                why_it_grows="Steam downloads shader caches per game and per driver version.",
                why_safe_to_delete="Only compiled shaders. Game files, prefixes, and saves are untouched.",
                regeneration_behavior="Re-downloaded or recompiled the next time the game launches.",
                reversible=True,
                targets=steam_shader_targets,
            )
        )
    return categories


def get_categories() -> list[CleanupCategory]:
    if is_linux():
        return _linux_shader_categories()
    if not is_windows():
        return []

    local = get_local_appdata()
    appdata = get_appdata()

    categories = []

    nvidia_targets = []
    for sub in ("DXCache", "GLCache", "NV_Cache", "ComputeCache"):
        p = os.path.join(local, "NVIDIA", sub)
        if os.path.isdir(p):
            nvidia_targets.append(CacheTarget(path=p))
    if nvidia_targets:
        categories.append(
            CleanupCategory(
                id="nvidia_shader_cache",
                name="NVIDIA shader cache",
                group="GPU",
                description="NVIDIA shader and driver caches (DXCache, GLCache). " + SHADER_WARNING,
                safety_level=SafetyLevel.LOW_RISK,
                targets=nvidia_targets,
            )
        )

    amd_targets = []
    for sub in ("DxCache", "GLCache"):
        p = os.path.join(local, "AMD", sub)
        if os.path.isdir(p):
            amd_targets.append(CacheTarget(path=p))
    if amd_targets:
        categories.append(
            CleanupCategory(
                id="amd_shader_cache",
                name="AMD shader caches",
                group="GPU",
                description="AMD shader caches. " + SHADER_WARNING,
                safety_level=SafetyLevel.LOW_RISK,
                targets=amd_targets,
            )
        )

    vulkan_targets = []
    vulkan_root = os.path.join(local, "Vulkan")
    if os.path.isdir(vulkan_root):
        vulkan_targets.append(CacheTarget(path=vulkan_root))
    gfx_cache = os.path.join(appdata, "Vulkan")
    if os.path.isdir(gfx_cache):
        vulkan_targets.append(CacheTarget(path=gfx_cache))
    if vulkan_targets:
        categories.append(
            CleanupCategory(
                id="vulkan_shader_cache",
                name="Vulkan shader caches",
                group="GPU",
                description="Vulkan pipeline caches. " + SHADER_WARNING,
                safety_level=SafetyLevel.LOW_RISK,
                targets=vulkan_targets,
            )
        )

    steam_shader_targets = []
    steam_appcache_targets = []
    for library in _steam_libraries():
        shadercache = os.path.join(library, "shadercache")
        if os.path.isdir(shadercache):
            steam_shader_targets.append(CacheTarget(path=shadercache))
        appcache = os.path.join(library, "appcache")
        if os.path.isdir(appcache):
            steam_appcache_targets.append(CacheTarget(path=appcache))

    if steam_shader_targets:
        categories.append(
            CleanupCategory(
                id="steam_shader_cache",
                name="Steam shader caches",
                group="GPU",
                description="Per-game shader caches managed by Steam. Recompiled on the next game launch. "
                + SHADER_WARNING,
                safety_level=SafetyLevel.LOW_RISK,
                targets=steam_shader_targets,
            )
        )

    if steam_appcache_targets:
        categories.append(
            CleanupCategory(
                id="steam_appcache",
                name="Steam app cache",
                group="GPU",
                description="Steam client cache data. Regenerated by Steam automatically.",
                safety_level=SafetyLevel.LOW_RISK,
                targets=steam_appcache_targets,
            )
        )

    return categories
