"""Generate the Windows version resource for the packaged executable.

Without it the .exe ships with an empty Properties -> Details tab, which on an
unsigned binary is the profile SmartScreen treats least generously.

Generated from `crapcleaner.constants.VERSION`, so it cannot drift from the version
the application reports.
"""

from __future__ import annotations

import os

TEMPLATE = """# Generated by scripts/version_info.py - do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({major}, {minor}, {patch}, {build}),
    prodvers=({major}, {minor}, {patch}, {build}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          '040904B0',
          [
            StringStruct('CompanyName', {company!r}),
            StringStruct('FileDescription', {description!r}),
            StringStruct('FileVersion', {version!r}),
            StringStruct('InternalName', {name!r}),
            StringStruct('LegalCopyright', {copyright!r}),
            StringStruct('OriginalFilename', {filename!r}),
            StringStruct('ProductName', {product!r}),
            StringStruct('ProductVersion', {version!r}),
          ],
        )
      ]
    ),
    VarFileInfo([VarStruct('Translation', [1033, 1200])]),
  ],
)
"""


def version_tuple(version: str) -> tuple[int, int, int, int]:
    """Turn a dotted version into the four integers a Windows resource needs.

    Missing components are zero, so "1.0.11" and "1.0.11.1" both work.
    """
    parts: list[int] = []
    for chunk in version.split(".")[:4]:
        digits = "".join(ch for ch in chunk if ch.isdigit())
        parts.append(int(digits) if digits else 0)
    while len(parts) < 4:
        parts.append(0)
    return parts[0], parts[1], parts[2], parts[3]


def render(version: str, filename: str = "CrapCleaner.exe") -> str:
    major, minor, patch, build = version_tuple(version)
    return TEMPLATE.format(
        major=major,
        minor=minor,
        patch=patch,
        build=build,
        version=version,
        company="CrapCleaner",
        description="Disk cleanup and storage analyzer",
        name="CrapCleaner",
        copyright="MIT licensed. See LICENSE.",
        filename=filename,
        product="CrapCleaner",
    )


def write(path: str, version: str, filename: str = "CrapCleaner.exe") -> str:
    directory = os.path.dirname(path)
    if directory:
        os.makedirs(directory, exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(render(version, filename))
    return path


def main() -> int:
    from crapcleaner.constants import VERSION

    target = os.path.join("build", "file_version_info.txt")
    write(target, VERSION)
    print(f"wrote {target} for version {VERSION}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
